version: "3"

services:
  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_turbo
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /projects/certs:/etc/nginx/certs
    ports:
      - 402:443
      - 401:80

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./apps/frontend
    depends_on:
      - backend

    ports:
      - 403:80
    restart: on-failure

  backend:
    image: backend
    container_name: backend
    build:
      context: ./apps/backend
    ports:
      - 404:3100
    restart: on-failure
